"""Voyagent canonical domain model — v0.

Source of truth for every agent, tool, and driver. Emits JSON Schema through
FastAPI's OpenAPI endpoint, which is consumed by `@voyagent/core` on the
TypeScript side via `openapi-typescript`.

See docs/CANONICAL_MODEL.md for design rationale and docs/DECISIONS.md for
the architectural choices these models encode (D2, D8, D9, D10).
"""

from .finance import (
    AccountType,
    BSPReport,
    BSPTransaction,
    BSPTransactionKind,
    Invoice,
    InvoiceLine,
    InvoiceStatus,
    JournalEntry,
    JournalLine,
    LedgerAccount,
    Payment,
    PaymentDirection,
    PaymentMethod,
    PaymentStatus,
    Receipt,
    Reconciliation,
    ReconciliationItem,
    ReconciliationOutcome,
    ReconciliationScope,
    ReconciliationSummary,
)
from .identity import (
    Client,
    ClientKind,
    Passenger,
    PassengerType,
    Passport,
    TaxRegistration,
)
from .lifecycle import (
    ActorKind,
    AuditEvent,
    AuditStatus,
    Document,
    DocumentKind,
    Enquiry,
    EnquiryDomain,
    EnquiryStatus,
)
from .primitives import (
    Address,
    CountryCode,
    CurrencyCode,
    E164Phone,
    Email,
    EmailStr,
    EntityId,
    Gender,
    IATACode,
    LanguageCode,
    LocalizedText,
    Money,
    NationalId,
    NationalIdKind,
    Period,
    Phone,
    TaxLine,
    TaxRegime,
    Timestamps,
)
from .travel import (
    BaggageAllowance,
    Booking,
    BookingStatus,
    CabinClass,
    Fare,
    FareComponent,
    FlightSegment,
    HotelBooking,
    HotelBookingStatus,
    HotelStay,
    Itinerary,
    ItinerarySegment,
    PNR,
    PNRStatus,
    SegmentStatus,
    Ticket,
    TicketStatus,
    TransferSegment,
    VisaChecklistItem,
    VisaFile,
    VisaStatus,
)

__all__ = [
    # primitives
    "Address",
    "CountryCode",
    "CurrencyCode",
    "E164Phone",
    "Email",
    "EmailStr",
    "EntityId",
    "Gender",
    "IATACode",
    "LanguageCode",
    "LocalizedText",
    "Money",
    "NationalId",
    "NationalIdKind",
    "Period",
    "Phone",
    "TaxLine",
    "TaxRegime",
    "Timestamps",
    # identity
    "Client",
    "ClientKind",
    "Passenger",
    "PassengerType",
    "Passport",
    "TaxRegistration",
    # travel
    "BaggageAllowance",
    "Booking",
    "BookingStatus",
    "CabinClass",
    "Fare",
    "FareComponent",
    "FlightSegment",
    "HotelBooking",
    "HotelBookingStatus",
    "HotelStay",
    "Itinerary",
    "ItinerarySegment",
    "PNR",
    "PNRStatus",
    "SegmentStatus",
    "Ticket",
    "TicketStatus",
    "TransferSegment",
    "VisaChecklistItem",
    "VisaFile",
    "VisaStatus",
    # finance
    "AccountType",
    "BSPReport",
    "BSPTransaction",
    "BSPTransactionKind",
    "Invoice",
    "InvoiceLine",
    "InvoiceStatus",
    "JournalEntry",
    "JournalLine",
    "LedgerAccount",
    "Payment",
    "PaymentDirection",
    "PaymentMethod",
    "PaymentStatus",
    "Receipt",
    "Reconciliation",
    "ReconciliationItem",
    "ReconciliationOutcome",
    "ReconciliationScope",
    "ReconciliationSummary",
    # lifecycle
    "ActorKind",
    "AuditEvent",
    "AuditStatus",
    "Document",
    "DocumentKind",
    "Enquiry",
    "EnquiryDomain",
    "EnquiryStatus",
]
