/* eslint-disable */
/**
 * This file is auto-generated by `pnpm -C packages/core codegen`.
 *
 * DO NOT EDIT BY HAND. Run the codegen pipeline to regenerate:
 *
 *   1. `infra/scripts/export_schemas.py` emits `packages/core/schemas.json`
 *      from the Pydantic models in `schemas/canonical/`.
 *   2. `json-schema-to-typescript` compiles that into this file.
 *
 * The placeholder type below is intentional — it keeps `@voyagent/core`
 * compilable before the first real codegen run and will be overwritten the
 * next time `pnpm -C packages/core codegen` succeeds.
 */

export type VoyagentCanonical = Record<string, unknown>;
